corsi_formazione/urls.py
from django.urls import path
from .views import indexC, viewA1, viewB1, viewC1, viewD1, viewE1, viewF1

app_name='corsi_formazione'

urlpatterns = [
    path('',indexC,name="indexC"),
    path("viewB1/<int:pk>", viewB1.as_view(), name="viewB1"),
    path("viewA1/", viewA1.as_view(), name="viewA1"),
    path("viewC1/", viewC1.as_view(), name="viewC1"),
    path("viewD1/", viewD1.as_view(), name="viewD1"),
    path("viewE1/", viewE1.as_view(), name="viewE1"),
    path("viewF1/", viewF1.as_view(), name="viewF1")
]

news/urls.py
from django.urls import path
from .views import home, articoloDetailView, lista_articoli, queryBase, giornalistaDetailView

app_name='news'

urlpatterns = [
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView.as_view(), name="articolo_detail"),
    path("lista_articoli/", lista_articoli.as_view(), name="lista_articoli1"),
    path("lista_articoli/<int:pk>", lista_articoli.as_view(), name="lista_articoli"),
    path("queryBase/", queryBase, name="queryBase"),
    path("giornalista/<int:pk>", giornalistaDetailView.as_view(), name="giornalista_detail")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base, index_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',base,name='base'),
    path('',index_root,name='index_root'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('eventi/',include("eventi.urls",namespace="eventi"))
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

corsi_formazione/models.py
from django.db import models
from datetime import datetime

class Corso(models.Model):
    titolo=models.CharField(max_length=50)
    descrizione=models.TextField()
    data_inizio=models.DateTimeField(default=datetime.now())
    data_fine=models.DateTimeField(default=datetime.now())
    posti_disponibili=models.IntegerField(default=0)
    

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name="Corso"
        verbose_name_plural="Corsi"

corsi_formazione/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
import datetime
from .models import Corso

def indexC(request):
    return render(request,"indexC.html")

class viewA1(ListView): #con l' utilizzo dela classe ListView ordino i corsi in ordine crescente in base alla data di inizio

    model = Corso
    template_name = "viewA1.html"
    context_object_name = "corsi"  
    ordering = ['data_inizio']

class viewB1(DetailView): #con l' utilizzo dela classe DetailView prendo l' id passato dalla pagina viewA.html per fare un dettaglio del corso
    model=Corso
    template_name="viewB1.html"

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context=super().get_context_data(**kwargs)
        context["corso"] = Corso.objects.get(id=pk)
        return context
    
class viewC1(ListView): #con l' utilizzo dela classe ListView prende i corsi iniziati dopo la data riportata
    model = Corso
    template_name = "viewC1.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["corsi"] = Corso.objects.filter(data_inizio__gt=(datetime.date(2025,5,1)))
        return context
    
class viewD1(ListView): #con l' utilizzo dela classe ListView restituisco i corsi con meno di 20 posti disponibili
    model=Corso
    template_name="viewD1.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["corsi"] = Corso.objects.filter(posti_disponibili__lte=20)
        return context

class viewE1(ListView): #con l' utilizzo dela classe ListView restituisco i corsi che finiscono prima della data riportata
    model = Corso
    template_name = "viewE1.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["corsi"] = Corso.objects.filter(data_inizio__lt=(datetime.date(2025,4,30)))
        return context
    
class viewF1(ListView): #con l' utilizzo dela classe ListView restituisco i corsi con max posti disponibili, min posti disponibili e totale posti disponibili
    model = Corso
    template_name = "viewF1.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["corsoMax"] = Corso.objects.order_by('-posti_disponibili').first()
        context["corsoMin"] = Corso.objects.order_by('posti_disponibili').first()
        allCorsi= Corso.objects.all()
        tot=0
        for corso in allCorsi:
            tot+=corso.posti_disponibili
        context["posti_disponibili"]=tot
        return context

corsi_formazione/templates/indexC.html
{% extends "base.html" %}
{% block title %}Index{% endblock title %}
{% block content %}

    <li><a href="{% url 'corsi_formazione:viewA1'%}">Lista dei Corsi</a></li>
    <li><a href="{% url 'corsi_formazione:viewB1' 1 %}">Dettagli dei Corsi</a></li>
    <li><a href="{% url 'corsi_formazione:viewC1'%}">Corsi che iniziano dopo il 01/05/2025</a></li>
    <li><a href="{% url 'corsi_formazione:viewD1'%}">Corsi con meno di 20 posti disponibili</a></li>
    <li><a href="{% url 'corsi_formazione:viewE1'%}">Corsi che terminano entro il 30/04/2025</a></li>
    <li><a href="{% url 'corsi_formazione:viewF1'%}">Statistiche Avanzate sui Corsi</a></li>

{% endblock content %}

corsi_formazione/templates/viewA1.html
{% extends "base.html" %}
{% block tiile %}View A{% endblock tiile %}
{% block content %}

<ul>
{% for corso in corsi %}
<li><p><strong>Titolo:</strong>
    <a href={% url 'corsi_formazione:viewB1' corso.id %}>{{corso.titolo}}</a>
    </p></li>
    <li><p><strong>Descrizione: </strong>{{corso.descrizione}}</p></li>
    <li><p><strong>Data inizio: </strong>{{corso.data_inizio}}</p></li>
    <li><p><strong>Data fine: </strong>{{corso.data_fine}}</p></li>
    <li><p><strong>Posti disponibili </strong>{{corso.posti_disponibili}}</p></li>
    <hr>
{% endfor %}
</ul>
{% endblock content %}

corsi_formazione/templates/viewB1.html
{% extends "base.html" %}
{% block title %}viewB{% endblock title %}
{% block content %}
    <h4><strong>Titolo: </strong></h4><p>{{corso.titolo}}</p>
    <h4><strong>Descrizione: </strong></h4><p>{{corso.descrizione}}</p>
    <h4><strong>Data inizio: </strong></h4><p>{{corso.data_inizio}}</p>
    <h4><strong>Data fine: </strong></h4><p>{{corso.data_fine}}</p>
    <h4><strong>Posti disponibili: </strong></h4><p>{{corso.posti_disponibili}}</p>
{% endblock content %}

corsi_formazione/templates/viewC1.html
{% extends "base.html" %}
{% block title %}viewC{% endblock title %}
{% block content %}

<ul>
    {% for corso in corsi %}
        <li><p><strong>Titolo: </strong>{{corso.titolo}}</p></li>
        <li><p><strong>Descrizione: </strong>{{corso.descrizione}}</p></li>
        <li><p><strong>Data inizio: </strong>{{corso.data_inizio}}</p></li>
        <li><p><strong>Data fine: </strong>{{corso.data_fine}}</p></li>
        <li><p><strong>Posti disponibili </strong>{{corso.posti_disponibili}}</p></li>
        <hr>
    {% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/viewD1.html
{% extends "base.html" %}
{% block title %}viewD{% endblock title %}
{% block content %}

<ul>
    {% for corso in corsi %}
        <li><p><strong>Titolo: </strong>{{corso.titolo}}</p></li>
        <li><p><strong>Descrizione: </strong>{{corso.descrizione}}</p></li>
        <li><p><strong>Data inizio: </strong>{{corso.data_inizio}}</p></li>
        <li><p><strong>Data fine: </strong>{{corso.data_fine}}</p></li>
        <li><p><strong>Posti disponibili </strong>{{corso.posti_disponibili}}</p></li>
        <hr>
    {% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/viewE1.html
{% extends "base.html" %}
{% block title %}viewE{% endblock title %}
{% block content %}

<ul>
    {% for corso in corsi %}
        <li><p><strong>Titolo: </strong>{{corso.titolo}}</p></li>
        <li><p><strong>Descrizione: </strong>{{corso.descrizione}}</p></li>
        <li><p><strong>Data inizio: </strong>{{corso.data_inizio}}</p></li>
        <li><p><strong>Data fine: </strong>{{corso.data_fine}}</p></li>
        <li><p><strong>Posti disponibili </strong>{{corso.posti_disponibili}}</p></li>
        <hr>
    {% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/viewF1.html
{% extends "base.html" %}
{% block title %}viewF{% endblock title %}
{% block content %}

    <ul>
        <li><strong>Corso con più posti disponibili: </strong>{{corsoMax.titolo}} {{corsoMax.posti_disponibili}} posti</li>
        <li><strong>Corso con meno posti disponibili: </strong>{{corsoMin.titolo}} {{corsoMin.posti_disponibili}} posti</li>
        <li><strong>Totale posti disponibili per tutti i corsi: </strong>{{posti_disponibili}}</li>
    </ul>

{% endblock content %}