forms_app/urls.py
from django.urls import path
from .views import contatti, lista_contatti, modifica_contatto, elimina_contatto

app_name='forms_app'

urlpatterns = [
    path('contattaci/', contatti, name='contatti'),
    path("lista-contatti/", lista_contatti.as_view(), name="lista-contatti"),
    path('elimina-contatto/<int:pk>/', elimina_contatto, name='elimina-contatto'),
    path('modifica-contatto/<int:pk>/', modifica_contatto, name='modifica-contatto'),
]

news/urls.py
from django.urls import path
from .views import home, articoloDetailView, lista_articoli, queryBase, giornalistaDetailView

app_name='news'

urlpatterns = [
    path('',home,name="homeview"),
    path("articoli/<int:pk>", articoloDetailView.as_view(), name="articolo_detail"),
    path("lista_articoli/", lista_articoli.as_view(), name="lista_articoli1"),
    path("lista_articoli/<int:pk>", lista_articoli.as_view(), name="lista_articoli"),
    path("queryBase/", queryBase, name="queryBase"),
    path("giornalista/<int:pk>", giornalistaDetailView.as_view(), name="giornalista_detail")
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index
 

app_name="prima_app"
urlpatterns=[
    path('homepage',homepage,name='homepage'),
    path('welcome',welcome,name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('',index,name='index')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base, index_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',base,name='base'),
    path('',index_root,name='index_root'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('news/',include("news.urls",namespace="news")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('voti/',include("voti.urls",namespace="voti")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('eventi/',include("eventi.urls",namespace="eventi"))
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

seconda_app/urls.py
from django.urls import path
from .views import es_if, if_else_elif, index2, es_for

app_name="seconda_app"
urlpatterns=[
    path('es_for',es_for,name='es_for'),
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('',index2,name='index2')
]

voti/urls.py
from django.urls import path
from .views import viewA, viewB, viewC, viewD

app_name='voti'

urlpatterns = [
    path("viewA/", viewA, name="viewA"),
    path("viewB/", viewB, name="viewB"),
    path("viewC/", viewC, name="viewC"),
    path("viewD/", viewD, name="viewD"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">Primo Progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Homepage</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">es if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">if else elif</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">for</a>
                </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                News
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'news:homeview'%}">Homepage</a>
                <a class="dropdown-item" href="{% url 'news:articolo_detail' 1 %}">Articolo detail</a>
                <a class="dropdown-item" href="{% url 'news:lista_articoli1'%}">Lista artcoli</a>
                <a class="dropdown-item" href="{% url 'news:queryBase' %}">query base</a>
                <a class="dropdown-item" href="{% url 'news:giornalista_detail' 1 %}">giornalista_detail</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Voti
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'voti:viewA'%}">viewA</a>
                <a class="dropdown-item" href="{% url 'voti:viewB'%}">viewB</a>
                <a class="dropdown-item" href="{% url 'voti:viewC'%}">viewC</a>
                <a class="dropdown-item" href="{% url 'voti:viewD'%}">viewD</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Eventi
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'eventi:viewA'%}">viewA</a>
                <a class="dropdown-item" href="{% url 'eventi:viewB'%}">viewB</a>
                <a class="dropdown-item" href="{% url 'eventi:viewC'%}">viewC</a>
                <a class="dropdown-item" href="{% url 'eventi:viewD'%}">viewD</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Corsi
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'corsi_formazione:indexC'%}">Index</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewA1'%}">viewA</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewB1' 1 %}">viewB</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewC1'%}">viewC</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewD1'%}">viewD</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewE1'%}">viewE</a>
                <a class="dropdown-item" href="{% url 'corsi_formazione:viewF1'%}">viewF</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Contatti
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
                <a class="dropdown-item" href="{% url 'forms_app:lista-contatti'%}">lista contatti</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              {% if request.user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <div class="dropdown-divider"></div>
                  <form id="logout-form" action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn ft-power" type="submit">Logout</button>
                  </form>
                </div>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Registrati</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
            </li>
          </ul>
        </div>
    </nav>

    <div class="container my-4">
    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index_root.html
{% extends "base.html" %}
{% block content %}
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
    </ol>
{% endblock content %}